import { UserStory, TestCase } from '../../../types';

export interface GeneratedTestCaseItem extends TestCase {
  vectorType: 'Functional / Happy Path' | 'Security / RBAC Gate' | 'Boundary / Threshold' | 'Edge Case / PII Governance' | 'Resilience / Recovery';
  targetAC: string;
}

export const generateMultiVectorTestCases = (story: UserStory): GeneratedTestCaseItem[] => {
  const now = new Date().toISOString();

  if (story.key.includes('204') || story.title.toLowerCase().includes('export') || story.title.toLowerCase().includes('governance')) {
    return [
      {
        id: 'tc-201',
        projectId: story.projectId,
        storyId: story.id,
        key: 'TC-201',
        title: 'Verify Workspace Admin can enable local data export toggle for team member',
        type: 'Automated',
        priority: 'Critical',
        status: 'Approved',
        isAiGenerated: true,
        aiConfidence: 98,
        tags: ['Admin', 'Compliance', 'BDD', 'Happy-Path'],
        lastExecutionStatus: 'Passed',
        vectorType: 'Functional / Happy Path',
        targetAC: story.acceptanceCriteria[0] || 'Admin can select any team member from dropdown',
        createdAt: now,
        updatedAt: now,
        steps: [
          { stepNumber: 1, action: 'Given that CloudAdmin is logged in to Admin Console and launch Policy Utility', expectedResult: 'Cloud Admin Console permissions dashboard loaded' },
          { stepNumber: 2, action: 'When user selects member "Sarah Jenkins (Data Analyst)" from dropdown', expectedResult: 'Member permissions policy panel populated' },
          { stepNumber: 3, action: 'Then toggle for "Enable member to export data to local storage" should be ON', expectedResult: 'Toggle switch in active ON position (aria-checked=true)' },
          { stepNumber: 4, action: 'When User turn OFF the toggle for export data', expectedResult: 'Toggle state changes to OFF and confirmation prompt shown' },
          { stepNumber: 5, action: 'Then the user is logged out of the application', expectedResult: 'Session ended and login page displayed' },
        ],
      },
      {
        id: 'tc-202',
        projectId: story.projectId,
        storyId: story.id,
        key: 'TC-202',
        title: 'Verify non-admin role is blocked from modifying data export policy',
        type: 'Automated',
        priority: 'Critical',
        status: 'Approved',
        isAiGenerated: true,
        aiConfidence: 96,
        tags: ['Security', 'RBAC', 'Negative-Gate'],
        lastExecutionStatus: 'Passed',
        vectorType: 'Security / RBAC Gate',
        targetAC: story.acceptanceCriteria[1] || 'Non-admin roles must receive 403 Forbidden',
        createdAt: now,
        updatedAt: now,
        steps: [
          { stepNumber: 1, action: 'Given Member user "Devin Chen" with non-admin permissions logs in', expectedResult: 'Standard user dashboard loaded' },
          { stepNumber: 2, action: 'When member attempts direct POST request to /api/v1/workspace/export-data', expectedResult: 'Server rejects request with HTTP 403 Forbidden' },
          { stepNumber: 3, action: 'Then UI renders access denied security banner', expectedResult: 'Zero-trust unauthorized access warning displayed' },
        ],
      },
      {
        id: 'tc-203',
        projectId: story.projectId,
        storyId: story.id,
        key: 'TC-203',
        title: 'Verify export payload limit threshold (>50MB) triggers chunked background stream without memory leak',
        type: 'Automated',
        priority: 'High',
        status: 'Approved',
        isAiGenerated: true,
        aiConfidence: 92,
        tags: ['Boundary', 'Performance', 'Threshold'],
        lastExecutionStatus: 'Passed',
        vectorType: 'Boundary / Threshold',
        targetAC: story.acceptanceCriteria[2] || 'Export payload exceeding 50MB must enforce chunked stream',
        createdAt: now,
        updatedAt: now,
        steps: [
          { stepNumber: 1, action: 'Given workspace contains 500,000 telemetry audit records totaling 75MB', expectedResult: 'Dataset indexed and ready for export' },
          { stepNumber: 2, action: 'When admin triggers full organizational export', expectedResult: 'System switches to asynchronous chunked background job' },
          { stepNumber: 3, action: 'Then download progress bar tracks chunk completion without UI freeze', expectedResult: 'File downloaded successfully with valid checksum' },
        ],
      },
      {
        id: 'tc-204',
        projectId: story.projectId,
        storyId: story.id,
        key: 'TC-204',
        title: 'Verify PII masking retains SHA-256 mask pattern when dataset contains unicode & special characters',
        type: 'Automated',
        priority: 'High',
        status: 'Approved',
        isAiGenerated: true,
        aiConfidence: 95,
        tags: ['Edge-Case', 'PII', 'Data-Governance'],
        lastExecutionStatus: 'Passed',
        vectorType: 'Edge Case / PII Governance',
        targetAC: story.acceptanceCriteria[3] || 'PII fields must be masked with SHA-256 hashes',
        createdAt: now,
        updatedAt: now,
        steps: [
          { stepNumber: 1, action: 'Given user records containing non-standard ASCII and emoji characters in name/address fields', expectedResult: 'Raw test data loaded in sandbox' },
          { stepNumber: 2, action: 'When PII masking engine executes export sanitization', expectedResult: 'Sensitive fields masked with consistent 64-char hex hash' },
          { stepNumber: 3, action: 'Then zero plain-text PII is exposed in CSV output', expectedResult: 'Compliance scanner verifies 0% PII leak' },
        ],
      },
      {
        id: 'tc-205',
        projectId: story.projectId,
        storyId: story.id,
        key: 'TC-205',
        title: 'Verify network drop or session timeout during export triggers safe state rollback',
        type: 'Automated',
        priority: 'Medium',
        status: 'Approved',
        isAiGenerated: true,
        aiConfidence: 91,
        tags: ['Resilience', 'Session-Timeout', 'Rollback'],
        lastExecutionStatus: 'Passed',
        vectorType: 'Resilience / Recovery',
        targetAC: story.acceptanceCriteria[4] || 'Session timeout during export must trigger safe state rollback',
        createdAt: now,
        updatedAt: now,
        steps: [
          { stepNumber: 1, action: 'Given active background data export in progress at 45% completion', expectedResult: 'Stream active' },
          { stepNumber: 2, action: 'When user auth token expires and WebSocket connection disconnects', expectedResult: 'Session invalidated gracefully' },
          { stepNumber: 3, action: 'Then partial temporary files are purged and resume token is issued upon re-login', expectedResult: 'System returns to clean idle state' },
        ],
      },
    ];
  }

  // Dynamic Generator for other stories
  const prefix = story.key.includes('104') ? 'TC-30' : story.key.includes('108') ? 'TC-40' : 'TC-50';

  return [
    {
      id: `${story.id}-tc-1`,
      projectId: story.projectId,
      storyId: story.id,
      key: `${prefix}1`,
      title: `Verify primary functional happy path for ${story.title}`,
      type: 'Automated',
      priority: 'High',
      status: 'Approved',
      isAiGenerated: true,
      aiConfidence: 97,
      tags: ['Functional', 'Happy-Path', 'BDD'],
      lastExecutionStatus: 'Passed',
      vectorType: 'Functional / Happy Path',
      targetAC: story.acceptanceCriteria[0] || 'Primary requirement fulfilled',
      createdAt: now,
      updatedAt: now,
      steps: [
        { stepNumber: 1, action: `Given authorized user initiates ${story.key} workflow`, expectedResult: 'Dashboard and workflow loaded' },
        { stepNumber: 2, action: `When valid inputs are provided according to acceptance criteria`, expectedResult: 'Action submitted successfully' },
        { stepNumber: 3, action: `Then system persists changes and displays confirmation`, expectedResult: 'Success status confirmed' },
      ],
    },
    {
      id: `${story.id}-tc-2`,
      projectId: story.projectId,
      storyId: story.id,
      key: `${prefix}2`,
      title: `Verify unauthorized role access gate and security boundary for ${story.key}`,
      type: 'Automated',
      priority: 'Critical',
      status: 'Approved',
      isAiGenerated: true,
      aiConfidence: 95,
      tags: ['Security', 'Negative-Test', 'RBAC'],
      lastExecutionStatus: 'Passed',
      vectorType: 'Security / RBAC Gate',
      targetAC: story.acceptanceCriteria[1] || 'Security boundary enforced',
      createdAt: now,
      updatedAt: now,
      steps: [
        { stepNumber: 1, action: 'Given user with insufficient permissions attempts action', expectedResult: 'Access gate triggered' },
        { stepNumber: 2, action: 'When request is submitted to backend endpoint', expectedResult: 'Request rejected with 401/403 status code' },
        { stepNumber: 3, action: 'Then appropriate security warning is shown in UI', expectedResult: 'Security alert displayed' },
      ],
    },
    {
      id: `${story.id}-tc-3`,
      projectId: story.projectId,
      storyId: story.id,
      key: `${prefix}3`,
      title: `Verify boundary conditions and payload thresholds for ${story.title}`,
      type: 'Automated',
      priority: 'High',
      status: 'Approved',
      isAiGenerated: true,
      aiConfidence: 93,
      tags: ['Boundary', 'Edge-Case', 'Validation'],
      lastExecutionStatus: 'Passed',
      vectorType: 'Boundary / Threshold',
      targetAC: story.acceptanceCriteria[2] || 'Boundary limits handled gracefully',
      createdAt: now,
      updatedAt: now,
      steps: [
        { stepNumber: 1, action: 'Given input fields populated with maximum boundary length values', expectedResult: 'Fields accept valid edge characters' },
        { stepNumber: 2, action: 'When field length exceeds upper limit by 1 character', expectedResult: 'Inline validation error prevents submission' },
        { stepNumber: 3, action: 'Then system maintains stability without crashing', expectedResult: 'Error cleared upon correction' },
      ],
    },
    {
      id: `${story.id}-tc-4`,
      projectId: story.projectId,
      storyId: story.id,
      key: `${prefix}4`,
      title: `Verify error recovery and session rollback under network failure for ${story.key}`,
      type: 'Automated',
      priority: 'Medium',
      status: 'Approved',
      isAiGenerated: true,
      aiConfidence: 90,
      tags: ['Resilience', 'Fault-Tolerance'],
      lastExecutionStatus: 'Passed',
      vectorType: 'Resilience / Recovery',
      targetAC: story.acceptanceCriteria[story.acceptanceCriteria.length - 1] || 'Session and fault recovery',
      createdAt: now,
      updatedAt: now,
      steps: [
        { stepNumber: 1, action: 'Given network connection throttling or simulated 504 gateway timeout', expectedResult: 'Retry interceptor active' },
        { stepNumber: 2, action: 'When operation fails due to network interrupt', expectedResult: 'Graceful retry prompt offered to user' },
        { stepNumber: 3, action: 'Then draft state is preserved without losing user inputs', expectedResult: 'User can retry seamlessly' },
      ],
    },
  ];
};
